#ifndef BGSUBTRACTORPLUGIN_GLOBAL_H
#define BGSUBTRACTORPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BGSUBTRACTORPLUGIN_LIB
# define BGSUBTRACTORPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define BGSUBTRACTORPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // BGSUBTRACTORPLUGIN_GLOBAL_H
